server:
  port: 8501
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: tcs-poc-ms-idgenerator-us-i2
  client:
    serviceUrl:
      defaultZone: http://tcs-poc-ms-eurekaserver-us-i2.us-east-1.elasticbeanstalk.com/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
spring:
  application:
    name: TCS-POC-MS-IDGENERATOR
logging:
  level:
    org.exampledriven.eureka: DEBUG