server:
  port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://tcs-poc-ms-eurekaserver.com/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
    
spring:
  application:
    name: TCS-POC-MS-IDGENERATOR
logging:
  level:
    org.exampledriven.eureka: DEBUG